package com.example.quote365

object QuoteData {
    var data = arrayOf(
        arrayOf("If you want your children to turn out well, spend twice as much time with them, and half as much money.", "Abigail Van Buren"),
        arrayOf("No man is good enough to govern another man without that other's consent.", "Abraham Lincoln"),
        arrayOf("Whatever you are, be a good one.", "Abraham Lincoln"),
        arrayOf("Let no feeling of discouragement prey upon you, and in the end you are sure to succeed.", "Abraham Lincoln"),
        arrayOf("It’s not the years in your life that count. It’s the life in your years.", "Abraham Lincoln"),
        arrayOf("Behind every adversity is an opportunity. If you lament over the adversity, you will miss the opportunity.", "Ajaero Tony Martins"),
        arrayOf("Strive not to be a success, but rather to be of value.", "Albert Einstein"),
        arrayOf("Logic will get you from A to B. Imagination will take you everywhere.", "Albert Einstein"),
        arrayOf("Great ideas often receive violent opposition from mediocre minds.", "Albert Einstein"),
        arrayOf("Not everything that can be counted counts, and not everything that counts can be counted.", "Albert Einstein"),
        arrayOf("If you can’t explain it simply, you don’t understand it well enough.", "Albert Einstein"),
        arrayOf("A person who never made a mistake never tried anything new.", "Albert Einstein"),
        arrayOf("The most common way people give up their power is by thinking they don’t have any.", "Alice Walker"),
        arrayOf("The most difficult thing is the decision to act, the rest is merely tenacity.", "Amelia Earhart"),
        arrayOf("There are two kinds of stones, as everyone knows, one of which rolls.", "Amelia Earhart"),
        arrayOf("Life shrinks or expands in proportion to one's courage", "Anais Nin"),
        arrayOf("Certain things catch your eye, but pursue only those that capture the heart.", "Ancient Indian Proverb"),
        arrayOf("To command is to serve, nothing more and nothing less.", "Andre Malraux"),
        arrayOf("No man will make a great leader who wants to do it all himself, or to get all the credit for doing it.", "Andrew Carnegie"),
        arrayOf("You are what you think. So just think big, believe big, act big, work big, give big, forgive big, laugh big, love big, and live big.", "Andrew Carnegie"),
        arrayOf("Whatever you do, be different-that was the advice my mother gave me, and I can’t think of better advice for an entrepreneur. If you’re different, you will stand out.", "Anita Roddick"),
        arrayOf("You have to look at leadership through the eyes of the followers and you have to live the message. What I have learned is that people become motivated when you guide them to the source of their own power and when you make heroes out of employees who personify what you want to see in the organization.", "Anita Roddick"),
        arrayOf("It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.", "Ann Landers"),
        arrayOf("The real measure of your wealth is how much you'd be worth if you lost all your money.", "Anonymous"),
        arrayOf("In business, you don’t get what you deserve, you get what you negotiate.", "Anonymous"),
        arrayOf("There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "Aristotle"),
        arrayOf("He who has never learned to obey cannot be a good commander.", "Aristotle"),
        arrayOf("First, have a definite, clear practical ideal: a goal, an objective. Second, have the necessary means to achieve your ends: wisdom, money, materials, and methods. Third, adjust all your means to that end.", "Aristotle"),
        arrayOf("One of the tests of leadership is the ability to recognize a problem before it becomes an emergency.", "Arnold Glasow"),
        arrayOf("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
        arrayOf("Nothing is impossible, the word itself says, I’m possible!", "Audrey Hepburn"),
        arrayOf("Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", "Ayn Rand"),
        arrayOf("The question isn’t who is going to let me, it’s who is going to stop me.", "Ayn Rand"),
        arrayOf("Every strike brings me closer to the next home run.", "Babe Ruth"),
        arrayOf("It’s hard to beat a person who never gives up.", "Babe Ruth"),
        arrayOf("Goals aren’t enough. You need goals plus deadlines: goals big enough to get excited about and deadline to make you run. One isn’t much good without the other, but together they can be tremendous.", "Ben Feldman"),
        arrayOf("The individual investor should act consistently as an investor and not as a speculator.", "Ben Graham"),
        arrayOf("An investment in knowledge pays the best interest.", "Benjamin Franklin"),
        arrayOf("Wealth is not his that has it, but his that enjoys it.", "Benjamin Franklin"),
        arrayOf("I didn’t fail the test. I just found 100 ways to do it wrong.", "Benjamin Franklin"),
        arrayOf("If you would not be forgotten, as soon as you are dead and rotten, either write things worth reading, or do things worth the writing.", "Benjamin Franklin"),
        arrayOf("You may be disappointed if you fail, but you are doomed if you don't try.", "Beverly Sills"),
        arrayOf("Leadership is unlocking people's potential to become better.", "Bill Bradley"),
        arrayOf("In order to succeed, your desire for success should be greater than your fear of failure.", "Bill Cosby"),
        arrayOf("Be nice to geeks, you'll probably end up working for one.", "Bill Gates"),
        arrayOf("As we look ahead into the next century, leaders will be those who empower others.", "Bill Gates"),
        arrayOf("Your most unhappy customers are your greatest source of learning.", "Bill Gates"),
        arrayOf("True leadership lies in guiding others to success. In ensuring that everyone is performing at their best, doing the work they are pledged to do and doing it well.", "Bill Owens"),
        arrayOf("Age is something that doesn’t matter, unless you are a cheese.", "Billie Burke"),
        arrayOf("If you want to lift yourself up, lift up someone else.", "Booker T. Washington"),
        arrayOf("Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "Booker T. Washington"),
        arrayOf("Become the kind of leader that people would follow voluntarily, even if you had no title or position.", "Brian Tracy"),
        arrayOf("Successful people are always looking for opportunities to help others. Unsuccessful people are asking, what’s in it for me?", "Brian Tracy"),
        arrayOf("Leaders think and talk about the solutions. Followers think and talk about the problems.", "Brian Tracy"),
        arrayOf("The successful warrior is the average man, with laser-like focus.", "Bruce Lee"),
        arrayOf("Simplicity is the key to brilliance.", "Bruce Lee"),
        arrayOf("The mind is everything. What you think, you become.", "Buddha"),
        arrayOf("Wealth after all is a relative thing since he that has little and wants less is richer than he that has much and wants more.", "Charles Caleb Colton"),
        arrayOf("We are all faced with a series of great opportunities brilliantly disguised as impossible situations.", "Charles R. Swindoll"),
        arrayOf("Life is 10% what happens to me and 90% of how I react to it.", "Charles Swindoll"),
        arrayOf("Not the cry, but the flight of a wild duck, leads the flock to fly and follow.", "Chinese Proverb"),
        arrayOf("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
        arrayOf("The person who says it cannot be done should not interrupt the person who is doing it.", "Chinese Proverb"),
        arrayOf("If plan A fails, remember there are 25 more letters.", "Chris Guillebeau"),
        arrayOf("You can never cross the ocean until you have the courage to lose sight of the shore.", "Christopher Columbus"),
        arrayOf("Everyday is a bank account, and time is our currency. No one is rich, no one is poor, we've got 24 hours each.", "Christopher Rice"),
        arrayOf("Frugality includes all the other virtues.", "Cicero"),
        arrayOf("There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", "Colin Powell"),
        arrayOf("Great leaders are almost always great simplifiers, who can cut through argument, debate, and doubt to offer a solution everybody can understand.", "Colin Powell"),
        arrayOf("Leadership is solving problems. The day soldiers stop bringing you their problems is the day you have stopped leading them. They have either lost confidence that you can help or concluded you do not care. Either case is a failure of leadership.", "Colin Powell"),
        arrayOf("Work hard, be kind, and amazing things will happen.", "Conan O’Brien"),
        arrayOf("Choose a job that you like, and you will never have to work a day in your life.", "Confucius"),
        arrayOf("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
        arrayOf("Everything has beauty, but not everyone can see.", "Confucius"),
        arrayOf("Remember that not getting what you want is sometimes a wonderful stroke of luck.", "Dalai Lama"),
        arrayOf("Happiness is not something readymade. It comes from your own actions.", "Dalai Lama"),
        arrayOf("Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", "Dale Carnegie"),
        arrayOf("Act enthusiastic and you will be enthusiastic.", "Dale Carnegie"),
        arrayOf("If you had to identify, in one word, the reason why the human race has not achieved, and never will achieve, its full potential, that word would be 'meetings.'", "Dave Barry"),
        arrayOf("You must gain control over your money or the lack of it will forever control you.", "Dave Ramsey"),
        arrayOf("Financial peace isn't the acquisition of stuff. It's learning to live on less than you make, so you can give money back and have money to invest. You can't win until you do this.", "Dave Ramsey"),
        arrayOf("What do you need to start a business? Three simple things: know your product better than anyone, know your customer, and have a burning desire to succeed.", "Dave Thomas"),
        arrayOf("A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", "David Brinkley"),
        arrayOf("It's how you deal with failure that determines how you achieve success.", "David Feherty"),
        arrayOf("Persist, don’t take no for an answer. If you’re happy to sit at your desk and not take any risk, you’ll be sitting at your desk for the next 20 years.", "David Rubenstein"),
        arrayOf("I am endlessly fascinated that playing football is considered a training ground for leadership, but raising children isn't.", "Dee Dee Myers"),
        arrayOf("People want to do business with you because you help them get what they want. They don’t do business with you to help you get what you want.", "Don Crowther"),
        arrayOf("Leadership is an action, not a position.", "Donald McGannon"),
        arrayOf("Customers don't expect you to be perfect. They do expect you to fix things when they go wrong.", "Donald Porter"),
        arrayOf("Don't necessarily avoid sharp edges. Occasionally, they are necessary to leadership.", "Donald Rumsfeld"),
        arrayOf("As long as you’re going to be thinking anyway, think big.", "Donald Trump"),
        arrayOf("A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others. He does not set out to be a leader, but becomes one by the equality of his actions and the integrity of his intent.", "Douglas MacArthur"),
        arrayOf("Never give an order that can't be obeyed.", "Douglas MacArthur"),
        arrayOf("Don’t worry about failure, you only have to be right once.", "Drew Houston"),
        arrayOf("Leadership is the art of getting someone else to do something you want done because he wants to do it.", "Dwight Eisenhower"),
        arrayOf("The supreme quality of leadership is integrity.", "Dwight Eisenhower"),
        arrayOf("Motivation is the art of getting people to do what you want them to do because they want to do it.", "Dwight Eisenhower"),
        arrayOf("You don’t lead by hitting people over the head-that’s assault, not leadership.", "Dwight Eisenhower"),
        arrayOf("We become what we think about.", "Earl Nightingale"),
        arrayOf("If we command our wealth, we shall be rich and free. If our wealth commands us, we are poor indeed.", "Edmund Burke"),
        arrayOf("He who loses money, loses much. He who loses a friend, loses much more. He who loses faith, loses all.", "Eleanor Roosevelt"),
        arrayOf("To handle yourself, use your head. To handle others, use your heart.", "Eleanor Roosevelt"),
        arrayOf("One's philosophy is not best expressed in words, it is expressed in the choices one makes, and the choices we make are ultimately our responsibility.", "Eleanor Roosevelt"),
        arrayOf("Do what you feel in your heart to be right, for you’ll be criticized anyway.", "Eleanor Roosevelt"),
        arrayOf("It takes as much energy to wish as it does to plan.", "Eleanor Roosevelt"),
        arrayOf("You gain strength, courage and confidence by every experience in which you really stop to look fear in the face. You must do the thing you think you cannot do.", "Eleanor Roosevelt"),
        arrayOf("Remember no one can make you feel inferior without your consent.", "Eleanor Roosevelt"),
        arrayOf("Wealth consists not in having great possessions, but in having few wants.", "Epictetus"),
        arrayOf("The leader has to be practical and a realist yet must talk the language of the visionary and the idealist.", "Eric Hoffer"),
        arrayOf("When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "Erma Bombeck"),
        arrayOf("Leadership is the key to 99% of all successful efforts.", "Erskine Bowles"),
        arrayOf("I never dreamed about success. I worked for it.", "Estée Lauder"),
        arrayOf("Trust your instincts.", "Estée Lauder"),
        arrayOf("User experience is everything. It always has been, but it’s undervalued and underinvested in. If you don’t know user-centered design, study it. Hire people who know it. Obsess over it. Live and breathe it. Get your whole company on board.", "Evan Williams"),
        arrayOf("Build your own dreams, or someone else will hire you to build theirs.", "Farrah Gray"),
        arrayOf("The only safe ship in a storm is leadership.", "Faye Wattleton"),
        arrayOf("I attribute my success to this: I never gave or took any excuse.", "Florence Nightingale"),
        arrayOf("The best revenge is massive success.", "Frank Sinatra"),
        arrayOf("Happiness is not in the mere possession of money, it lies in the joy of achievement, in the thrill of creative effort.", "Franklin D. Roosevelt"),
        arrayOf("That which does not kill us makes us stronger.", "Friedrich Nietzsche"),
        arrayOf("To do great things is difficult, but to command great things is more difficult.", "Friedrich Nietzsche"),
        arrayOf("There are three essentials to leadership: humility, clarity and courage.", "Fuchan Yuan"),
        arrayOf("The secret of a leader lies in the tests he has faced over the whole course of his life and the habit of action he develops in meeting those tests.", "Gail Sheehy"),
        arrayOf("Stay self-funded as long as possible.", "Garrett Camp"),
        arrayOf("Everything you’ve ever wanted is on the other side of fear.", "George Addair"),
        arrayOf("It is never too late to be what you might have been.", "George Eliot"),
        arrayOf("It’s good to have money and the things that money can buy, but it’s good, too, to check up once in a while and make sure that you haven’t lost the things that money can’t buy.", "George Lorimer"),
        arrayOf("Never tell people how to do things. Tell them what to do and they will surprise you with their ingenuity.", "George Patton"),
        arrayOf("A good plan violently executed now is better than a perfect plan executed next week.", "George Patton"),
        arrayOf("Lead me, follow me, or get out of my way.", "George Patton"),
        arrayOf("I’m only rich because I know when I’m wrong, I basically have survived by recognizing my mistakes.", "George Soros"),
        arrayOf("Dreaming, after all, is a form of planning.", "Gloria Steinem"),
        arrayOf("Life is what we make it, always has been, always will be.", "Grandma Moses"),
        arrayOf("Ideas are easy. Implementation is hard.", "Guy Kawasaki"),
        arrayOf("Don’t wait for perfection. Life isn’t perfect. Do the best you can and ship. Real people ship, and then they test and then they ship again. Then you wake up one day and you have something insanely great.", "Guy Kawasaki"),
        arrayOf("Men make history and not the other way around. In periods where there is no leadership, society stands still. Progress occurs when courageous, skillful leaders seize the opportunity to change things for the better.", "Harry S. Truman"),
        arrayOf("The growth and development of people is the highest calling of leadership.", "Harvey Firestone"),
        arrayOf("When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", "Helen Keller"),
        arrayOf("Wealth is the ability to fully experience life.", "Henry David Thoreau"),
        arrayOf("Go confidently in the direction of your dreams. Live the life you have imagined.", "Henry David Thoreau"),
        arrayOf("When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", "Henry Ford"),
        arrayOf("Whether you think you can or you think you can’t, you’re right.", "Henry Ford"),
        arrayOf("It’s not the employer who pays the wages. Employers only handle the money. It’s the customer who pays the wages.", "Henry Ford"),
        arrayOf("If money is your hope for independence you will never have it. The only real security that a man will have in this world is a reserve of knowledge, experience, and ability.", "Henry Ford"),
        arrayOf("A real entrepreneur is somebody who has no safety net underneath them.", "Henry Kravis"),
        arrayOf("You must be very patient, very persistent. The world isn’t going to shower gold coins on you just because you have a good idea. You’re going to have to work like crazy to bring that idea to the attention of people. They’re not going to buy it unless they know about it.", "Herb Kelleher"),
        arrayOf("I cannot give you the formula for success, but I can give you the formula for failure, which is: Try to please everybody.", "Herbert Swope"),
        arrayOf("Contrary to popular opinion, leadership is not a reserved position for a particular group of people who were elected or appointed, ordained or enthroned. Leadership is self-made, self-retained, self-inculcated and then exposed through a faithful, sincere and exemplary life.", "Israelmore Avivor"),
        arrayOf("It is our choices, that show what we truly are, far more than our abilities.", "J. K. Rowling"),
        arrayOf("Buy when everyone else is selling and hold until everyone else is buying. That’s not just a catchy slogan. It’s the very essence of successful investing.", "J. Paul Getty"),
        arrayOf("Everyone has an idea, but it’s really about executing the idea and attracting other people to help you with the idea.", "Jack Dorsey"),
        arrayOf("Life is not always a matter of holding good cards, but sometimes playing a poor hand well.", "Jack London"),
        arrayOf("If you can't swallow your pride, you can't lead. Even the highest mountain had animals that step on it.", "Jack Weatherford"),
        arrayOf("Good business leaders create a vision, articulate the vision, passionately own the vision, and relentlessly drive it to completion.", "Jack Welch"),
        arrayOf("I was never the smartest guy in the room. From the first person I hired, I was never the smartest guy in the room. And that's a big deal. And if you're going to be a leader, if you're a leader and you're the smartest guy in the world, in the room, you've got real problems.", "Jack Welch"),
        arrayOf("Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.", "Jack Welch"),
        arrayOf("Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", "Jamie Paolinetti"),
        arrayOf("Fall seven times and stand up eight.", "Japanese Proverb"),
        arrayOf("Projections are just bullshit. They’re just guesses.", "Jason Fried"),
        arrayOf("I knew that if I failed I wouldn’t regret that, but I knew the one thing I might regret is not trying.", "Jeff Bezos"),
        arrayOf("We see our customers as invited guests to a party, and we are the hosts. It’s our job every day to make every important aspect of the customer experience a little bit better.", "Jeff Bezos"),
        arrayOf("Today I will do what others won’t, so tomorrow I can accomplish what others can’t.", "Jerry Rice"),
        arrayOf("Leadership cannot just go along to get along. Leadership must meet the moral challenge of the day.", "Jesse Jackson"),
        arrayOf("The battles that count aren't the ones for gold medals. The struggles within yourself, the invisible battles inside all of us, that's where it's at.", "Jesse Owens"),
        arrayOf("Ask and it will be given to you. Search and you will find. Knock and the door will be opened for you.", "Jesus"),
        arrayOf("The challenge of leadership is to be strong, but not rude; be kind, but not weak; be bold, but not bully; be thoughtful, but not lazy; be humble, but not timid; be proud, but not arrogant; have humor, but without folly.", "Jim Rohn"),
        arrayOf("Better understated than overstated. Let people be surprised that it was more than you promised and easier than you said.", "Jim Rohn"),
        arrayOf("Formal education will make you a living. Self-education will make you a fortune.", "Jim Rohn"),
        arrayOf("Either you run the day, or the day runs you.", "Jim Rohn"),
        arrayOf("A great person attracts great people and knows how to hold them together.", "Johann Wolfgang von Goethe"),
        arrayOf("Many people take no care of their money till they come nearly to the end of it, and others do just the same with their time.", "Johann Wolfgang von Goethe"),
        arrayOf("Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "Johann Wolfgang von Goethe"),
        arrayOf("If you have trouble imagining a 20% loss in the stock market, you shouldn’t be in stocks.", "John Bogle"),
        arrayOf("Leadership and learning are indispensable to each other.", "John F. Kennedy"),
        arrayOf("Leaders are not, as we are often led to think, people who go along with huge crowds following them. Leaders are people who go their own way without caring, or even looking to see, whether anyone is following them. 'Leadership qualities' are not the qualities that enable people to attract followers, but those that enable them to do without them. They include, at the very least, courage, endurance, patience, humor, flexibility, resourcefulness, stubbornness, a keen sense of reality, and the ability to keep a cool and clear head, even when things are going badly. True leaders, in short, do not make people into followers, but into other leaders.", "John Holt"),
        arrayOf("A competent leader can get efficient service from poor troops, while on the contrary an incapable leader can demoralize the best of troops.", "John J Pershing"),
        arrayOf("All of the great leaders have had one characteristic in common: it was the willingness to confront unequivocally the major anxiety of their people in their time. This, and not much else, is the essence of leadership.", "John Kenneth Galbraith"),
        arrayOf("When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down ‘happy’. They told me I didn’t understand the assignment, and I told them they didn’t understand life.", "John Lennon"),
        arrayOf("A leader is one who knows the way, goes the way, and shows the way.", "John Maxwell"),
        arrayOf("Leaders must be close enough to relate to others, but far enough ahead to motivate them.", "John Maxwell"),
        arrayOf("A great leader's courage to fulfill his vision comes from passion, not position.", "John Maxwell"),
        arrayOf("People buy into the leader before they buy into the vision.", "John Maxwell"),
        arrayOf("Leadership is influence.", "John Maxwell"),
        arrayOf("Leadership is not about titles, positions or flowcharts. It is about one life influencing another.", "John Maxwell"),
        arrayOf("A good leader is a person who takes a little more than his share of the blame and a little less than his share of the credit.", "John Maxwell"),
        arrayOf("If your actions inspire others to dream more, learn more, do more and become more, you are a leader.", "John Quincy Adams"),
        arrayOf("Real leaders are ordinary people with extraordinary determinations.", "John Seaman Garns"),
        arrayOf("Courage is being scared to death, but saddling up anyway.", "John Wayne"),
        arrayOf("Great leaders are not defined by the absence of weakness, but rather by the presence of clear strengths.", "John Zenger"),
        arrayOf("A wise person should have money in their head, but not in their heart.", "Jonathan Swift"),
        arrayOf("If your ship doesn’t come in, swim out to meet it!", "Jonathan Winters"),
        arrayOf("When you find an idea that you just can’t stop thinking about, that’s probably a good one to pursue.", "Josh James"),
        arrayOf("Challenges are what make life interesting and overcoming them is what makes life meaningful.", "Joshua J. Marine"),
        arrayOf("What we really want to do is what we are really meant to do. When we do what we are meant to do, money comes to us, doors open for us, we feel useful, and the work we do feels like play to us.", "Julia Cameron"),
        arrayOf("The greatest leaders mobilize others by coalescing people around a shared vision.", "Ken Blanchard"),
        arrayOf("You don't lead by pointing and telling people some place to go. You lead by going to that place and making a case.", "Ken Kesey"),
        arrayOf("The key to successful leadership today is influence, not authority.", "Kenneth Blanchard"),
        arrayOf("Life is about making an impact, not making an income.", "Kevin Kruse"),
        arrayOf("Life isn't about getting and having, it's about giving and being.", "Kevin Kruse"),
        arrayOf("If you’ve got an idea, start today. There’s no better time than now to get going. That doesn’t mean quit your job and jump into your idea 100 percent from day one, but there’s always small progress that can be made to start the movement.", "Kevin Systrom"),
        arrayOf("If you don’t value your time, neither will others. Stop giving away your time and talents. Value what you know; start charging for it.", "Kim Garst"),
        arrayOf("There is a difference between being a leader and being a boss. Both are based on authority. A boss demands blind obedience, a leader earns his authority through understanding and trust.", "Klaus Balkenhol"),
        arrayOf("When I let go of what I am, I become what I might be.", "Lao Tzu"),
        arrayOf("A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.", "Lao Tzu"),
        arrayOf("A journey of a thousand miles must begin with a single step.", "Lao Tzu"),
        arrayOf("Always deliver more than expected.", "Larry Page"),
        arrayOf("If the wind will not serve, take to the oars.", "Latin Proverb"),
        arrayOf("It is absurd that a man should rule others, who cannot rule himself.", "Latin Proverb"),
        arrayOf("Even a correct decision is wrong when it was taken too late.", "Lee Iacocca"),
        arrayOf("I have been impressed with the urgency of doing. Knowing is not enough, we must apply. Being willing is not enough, we must do.", "Leonardo da Vinci"),
        arrayOf("Too many of us are not living our dreams because we are living our fears.", "Les Brown"),
        arrayOf("Wonder what your customer really wants? Ask. Don’t tell.", "Lisa Stone"),
        arrayOf("Never tell your problems to anyone, 20 percent don’t care and the other 80 percent are glad you have them.", "Lou Holtz"),
        arrayOf("It's your place in the world. It's your life. Go on and do all you can with it, and make it the life you want to live.", "Mae Jemison"),
        arrayOf("Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"),
        arrayOf("Every worthwhile accomplishment, big or little, has its stages of drudgery and triumph: a beginning, a struggle and a victory.", "Mahatma Gandhi"),
        arrayOf("You must be the change you wish to see in the world.", "Mahatma Gandhi"),
        arrayOf("Teach thy tongue to say, I do not know, and thous shalt progress.", "Maimonides"),
        arrayOf("The secret to successful hiring is this: look for the people who want to change the world.", "Marc Benioff"),
        arrayOf("We live in a society obsessed with public opinion. But leadership has never been about popularity.", "Marco Rubio"),
        arrayOf("Never doubt that a small group of thoughtful, concerned citizens can change world. Indeed it is the only thing that ever has.", "Margaret Mead"),
        arrayOf("Don't follow the crowd, let the crowd follow you.", "Margaret Thatcher"),
        arrayOf("Leadership is a series of behaviors rather than a role for heroes.", "Margaret Wheatley"),
        arrayOf("Never work just for money or for power. They won’t save your soul or help you sleep at night.", "Marian Wright Edelman"),
        arrayOf("Do an evening review at the end of the day to reflect on what went well, and what you’d do differently next time.", "Marilyn Suttle"),
        arrayOf("If everything seems under control, you’re just not going fast enough.", "Mario Andretti"),
        arrayOf("It’s not about money or connections. It’s the willingness to outwork and outlearn everyone when it comes to your business. And if it fails, you learn from what happened and do a better job next time.", "Mark Cuban"),
        arrayOf("Leaders live by choice, not by accident.", "Mark Gorma"),
        arrayOf("The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"),
        arrayOf("The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into smaller manageable tasks, and then starting on the first one.", "Mark Twain"),
        arrayOf("Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails, Explore, Dream, Discover.", "Mark Twain"),
        arrayOf("If you just work on stuff that you like and you’re passionate about, you don’t have to have a master plan with how things will play out.", "Mark Zuckerberg"),
        arrayOf("The biggest risk is not taking any risk. In a world that’s changing really quickly, the only strategy that is guaranteed to fail is not taking risks.", "Mark Zuckerberg"),
        arrayOf("If you do the things that are easier first, then you can actually make a lot of progress.", "Mark Zuckerberg"),
        arrayOf("Our lives begin to end the day we become silent about things that matter.", "Martin Luther King Jr."),
        arrayOf("The ultimate measure of a man is not where he stands in moments of comfort, but where he stands at times of challenge and controversy.", "Martin Luther King Jr."),
        arrayOf("Leadership should be more participative than directive, more enabling than performing.", "Mary D. Poole"),
        arrayOf("Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.", "Mary Kay Ash"),
        arrayOf("The first responsibility of a leader is to define reality. The last is to say thank you. In between, the leader is a servant.", "Max DePree"),
        arrayOf("A man who wants to lead the orchestra must turn his back on the crowd.", "Max Lucado"),
        arrayOf("If one is lucky, a solitary fantasy can totally transform one million realities.", "Maya Angelou"),
        arrayOf("You can only become truly accomplished at something you love. Don’t make money your goal. Instead, pursue the things you love doing, and then do them so well that people can’t take their eyes off you.", "Maya Angelou"),
        arrayOf("I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "Maya Angelou"),
        arrayOf("You can’t use up creativity. The more you use, the more you have.", "Maya Angelou"),
        arrayOf("Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "Maya Angelou"),
        arrayOf("The price of inaction is far greater than then cost of a mistake.", "Meg Whitman"),
        arrayOf("Don’t be afraid to assert yourself, have confidence in your abilities, and don’t let the bastards get you down.", "Michael Bloomberg"),
        arrayOf("There are a lot of things that go into creating success. I don’t like to do just the things I like to do. I like to do things that cause the company to succeed. I don’t spend a lot of time doing my favorite activities.", "Michael Dell"),
        arrayOf("Ideas are commodity. Execution of them is not.", "Michael Dell"),
        arrayOf("I've missed more than 9000 shots in my career. I've lost almost 300 games. Twenty six times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan"),
        arrayOf("Earn your leadership every day.", "Michael Jordan"),
        arrayOf("The greater danger for most of us lies not in setting our aim too high and falling short, but in setting our aim too low and achieving our mark.", "Michelangelo"),
        arrayOf("My own definition of leadership is this: The capacity and the will to rally men and women to a common purpose and the character which inspires confidence.", "Montgomery"),
        arrayOf("I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", "Muhammad Ali"),
        arrayOf("You don’t need a title to be a leader.", "Multiple Attributions"),
        arrayOf("Take time to deliberate, but when the time for action has arrived, stop thinking and go in.", "Napoleon Bonaparte"),
        arrayOf("A leader is a dealer in hope.", "Napoleon Bonaparte"),
        arrayOf("When I give a minister an order, I leave it to him to find the means to carry it out.", "Napoleon Bonaparte"),
        arrayOf("Whatever the mind of man can conceive and believe, it can achieve.", "Napoleon Hill"),
        arrayOf("It is better to lead from behind and to put others in front, especially when you celebrate victory when nice things occur. You take the front line when there is danger. Then people will appreciate your leadership.", "Nelson Mandela"),
        arrayOf("Remember to celebrate milestones as you prepare for the road ahead.", "Nelson Mandela"),
        arrayOf("The critical ingredient is getting off your butt and doing something. It’s as simple as that. A lot of people have ideas, but there are few who decide to do something about them now. Not tomorrow. Not next week. But today. The true entrepreneur is a doer, not a dreamer.", "Nolan Bushnell"),
        arrayOf("Leadership is a potent combination of strategy and character. But if you must be without one, be without the strategy.", "Norman Schwarzkopf"),
        arrayOf("Dream big and dare to fail", "Norman Vaughan"),
        arrayOf("Empty pockets never held anyone back. Only empty heads and empty hearts can do that.", "Norman Vincent Peale"),
        arrayOf("Change your thoughts and you change your world.", "Norman Vincent Peale"),
        arrayOf("You become what you believe.", "Oprah Winfrey"),
        arrayOf("Do the one thing you think you cannot do. Fail at it. Try again. Do better the second time. The only people who never tumble are those who never mount the high wire. This is your moment. Own it.", "Oprah Winfrey"),
        arrayOf("The big secret in life is that there is no big secret. Whatever your goal, you can get there if you’re willing to work.", "Oprah Winfrey"),
        arrayOf("If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "Oprah Winfrey"),
        arrayOf("A ruler should be slow to punish and swift to reward.", "Ovid"),
        arrayOf("Money is a terrible master but an excellent servant.", "P.T. Barnum"),
        arrayOf("Every child is an artist. The problem is how to remain an artist once he grows up.", "Pablo Picasso"),
        arrayOf("I'd like to live as a poor man with lots of money.", "Pablo Picasso"),
        arrayOf("To have long term success as a coach or in any position of leadership, you have to be obsessed in some way.", "Pat Riley"),
        arrayOf("Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.", "Paul Samuelson"),
        arrayOf("So much of what we call management consists in making it difficult for people to work.", "Peter Drucker"),
        arrayOf("Leadership is lifting a person's vision to high sights, the raising of a person's performance to a higher standard, the building of a personality beyond its normal limitations.", "Peter Drucker"),
        arrayOf("Management is doing things right, leadership is doing the right things.", "Peter Drucker"),
        arrayOf("Effective leadership is not about making speeches or being liked, leadership is defined by results not attributes.", "Peter Drucker"),
        arrayOf("The stock market is filled with individuals who know the price of everything, but the value of nothing.", "Phillip Fisher"),
        arrayOf("If you’re passionate about something and you work hard, then I think you will be successful.", "Pierre Omidyar"),
        arrayOf("No wealth can ever make a bad man at peace with himself.", "Plato"),
        arrayOf("We can easily forgive a child who is afraid of the dark, the real tragedy of life is when men are afraid of the light.", "Plato"),
        arrayOf("A good general not only sees the way to victory, he also knows when victory is impossible.", "Polybius"),
        arrayOf("Anyone can hold the helm when the sea is calm.", "Publilius Syrus"),
        arrayOf("We are not interested in the possibilities of defeat, they do not exist.", "Queen Victoria"),
        arrayOf("I start with the premise that the function of leadership is to produce more leaders, not more followers.", "Ralph Nader"),
        arrayOf("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
        arrayOf("Money often costs too much.", "Ralph Waldo Emerson"),
        arrayOf("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
        arrayOf("If you’re not a risk taker, you should get the hell out of business.", "Ray Kroc"),
        arrayOf("Successful leaders see the opportunities in every difficulty rather than the difficulty in every opportunity", "Reed Markham"),
        arrayOf("If you are not embarrassed by the first version of your product, you’ve launched too late.", "Reid Hoffman"),
        arrayOf("Success is no longer a simple ascension of steps. You need to climb sideways and sometimes down, and sometimes you need to swing from the jungle gym and establish your own turf somewhere else on the playground.", "Reid Hoffman"),
        arrayOf("When buying shares, ask yourself, would you buy the whole company?", "Rene Rivkin"),
        arrayOf("The very essence of leadership is that you have to have a vision. It's got to be a vision you articulate clearly and forcefully on every occasion. You can't blow an uncertain trumpet.", "Reverend Theodore Hesburgh"),
        arrayOf("Business opportunities are like buses: there’s always another one coming.", "Richard Branson"),
        arrayOf("You don’t learn to walk by following rules. You learn by doing and falling over.", "Richard Branson"),
        arrayOf("Screw it, Let’s do it!", "Richard Branson"),
        arrayOf("When you’re first thinking through an idea, it’s important not to get bogged down in complexity. Thinking simply and clearly is hard to do.", "Richard Branson"),
        arrayOf("What business should you start today? One that you are passionate about, has a big market opportunity, can be up and running quickly, and that doesn’t require a lot of initial capital. Think Internet, apps, e-commerce, and mobile.", "Richard Harroch"),
        arrayOf("It’s almost always harder to raise capital than you thought it would be, and it always takes longer. So plan for that.", "Richard Harroch"),
        arrayOf("Business is like poker. You have to be able to read people. You have to understand the odds of a particular endeavor. You need to make calculated bets. And you have to get lucky.", "Richard Harroch"),
        arrayOf("If you want to build a successful business, make sure you have three things-a big market opportunity, great people, and more than enough capital.", "Richard Harroch"),
        arrayOf("Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.", "Robert Frost"),
        arrayOf("How many millionaires do you know who have become wealthy by investing in savings accounts? I rest my case.", "Robert G. Allen"),
        arrayOf("It's not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for.", "Robert Kiyosaki"),
        arrayOf("Don’t let the fear of losing be greater than the excitement of winning.", "Robert Kiyosaki"),
        arrayOf("I stand up on my desk to remind myself that we must constantly look at things in a different way.", "Robin Williams"),
        arrayOf("Let him who would enjoy a good future waste none of his present.", "Roger Babson"),
        arrayOf("There are no traffic jams along the extra mile.", "Roger Staubach"),
        arrayOf("Any time is a good time to start a company.", "Ron Conway"),
        arrayOf("The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", "Ronald Reagan"),
        arrayOf("I have learned over the years that when one's mind is made up, this diminishes fear.", "Rosa Parks"),
        arrayOf("A leader takes people where they want to go. A great leader takes people where they don't necessarily want to go, but ought to be.", "Rosalynn Carter"),
        arrayOf("Lead and inspire people. Don’t try to manage and manipulate people. Inventories can be managed but people must be led.", "Ross Perot"),
        arrayOf("High expectations are the key to everything.", "Sam Walton"),
        arrayOf("Appreciate everything your associates do for the business. Nothing else can quite substitute for a few well-chosen, well-timed, sincere words of praise. They’re absolutely free and worth a fortune.", "Sam Walton"),
        arrayOf("Outstanding leaders go out of their way to boost the self-esteem of their personnel. If people believe in themselves, it's amazing what they can accomplish.", "Sam Walton"),
        arrayOf("Nothing will ever be attempted if all possible objections must first be overcome.", "Samuel Johnson"),
        arrayOf("He who has great power should use it lightly.", "Seneca"),
        arrayOf("It is not the man who has too little, but the man who craves more, that is poor.", "Seneca"),
        arrayOf("Leadership is the art of giving people a platform for spreading ideas that work.", "Seth Godin"),
        arrayOf("Waiting for perfect is never as smart as making progress.", "Seth Godin"),
        arrayOf("The secret of leadership is simple: Do what you believe in. Paint a picture of the future. Go there. People will follow.", "Seth Godin"),
        arrayOf("If you're offered a seat on a rocket ship, don't ask what seat! Just get on.", "Sheryl Sandberg"),
        arrayOf("Done is better than perfect.", "Sheryl Sandberg"),
        arrayOf("In between goals is a thing called life, that has to be lived and enjoyed.", "Sid Caesar"),
        arrayOf("What good is an idea if it remains an idea? Try. Experiment. Iterate. Fail. Try again. Change the world.", "Simon Sinek"),
        arrayOf("Education costs money. But then so does ignorance.", "Sir Claus Moser"),
        arrayOf("The four most expensive words in the English language are, This time it’s different.", "Sir John Templeton"),
        arrayOf("The secret of change is to focus all of your energy, not on fighting the old, but on building the new.", "Socrates"),
        arrayOf("An unexamined life is not worth living.", "Socrates"),
        arrayOf("He who has learned how to obey will know how to command.", "Solon"),
        arrayOf("Management is efficiency in climbing the ladder of success, leadership determines whether the ladder is leaning against the right wall.", "Stephen Covey"),
        arrayOf("Effective leadership is putting first things first. Effective management is discipline, carrying it out.", "Stephen Covey"),
        arrayOf("I am not a product of my circumstances. I am a product of my decisions.", "Stephen Covey"),
        arrayOf("Always treat your employees exactly as you want them to treat your best customers.", "Stephen Covey"),
        arrayOf("What you do has far greater impact than what you say.", "Stephen Covey"),
        arrayOf("A cowardly leader is the most dangerous of men.", "Stephen King"),
        arrayOf("You shouldn’t focus on why you can’t do something, which is what most people do. You should focus on why perhaps you can, and be one of the exceptions.", "Steve Case"),
        arrayOf("Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"),
        arrayOf("Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.", "Steve Jobs"),
        arrayOf("My job is not to be easy on people. My job is to take these great people we have and to push them and make them even better.", "Steve Jobs"),
        arrayOf("I’m convinced that about half of what separates the successful entrepreneurs from the non-successful ones is pure perseverance.", "Steve Jobs"),
        arrayOf("Sometimes when you innovate, you make mistakes. It is best to admit them quickly and get on with improving your other innovations.", "Steve Jobs"),
        arrayOf("It’s more fun to be a pirate than to join the navy.", "Steve Jobs"),
        arrayOf("Here’s to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes. The ones who see things differently. They’re not fond of rules. And they have no respect for the status quo. You can quote them, disagree with them, glorify or vilify them. About the only thing you can’t do is ignore them. Because they change things. They push the human race forward. And while some may see them as the crazy ones, we see genius. Because the people who are crazy enough to think they can change the world, are the ones who do.", "Steve Jobs"),
        arrayOf("Don't be trapped by dogma-which is living with the results of other people's thinking. Don't let the noise of other's opinions drown out your own inner voice. And most important, have the courage to follow your heart and intuition. They somehow already know what you truly want to become. Everything else is secondary.", "Steve Jobs"),
        arrayOf("You can’t connect the dots looking forward. You can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something, your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.", "Steve Jobs"),
        arrayOf("When you first start off trying to solve a problem, the first solutions you come up with are very complex, and most people stop there. But if you keep going, and live with the problem and peel more layers of the onion off, you can often times arrive at some very elegant and simple solutions. Most people just don’t put in the time or energy to get there.", "Steve Jobs"),
        arrayOf("Innovation distinguishes between a leader and a follower.", "Steve Jobs"),
        arrayOf("Be so good they can’t ignore you.", "Steve Martin"),
        arrayOf("Early to bed, early to rise, work like hell and advertise.", "Ted Turner"),
        arrayOf("Do what you can, where you are, with what you have.", "Teddy Roosevelt"),
        arrayOf("The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint enough to keep from meddling with them while they do it.", "Theodore Roosevelt"),
        arrayOf("The most important single ingredient in the formula of success is knowing how to get along with people.", "Theodore Roosevelt"),
        arrayOf("Believe you can and you’re halfway there.", "Theodore Roosevelt"),
        arrayOf("I have not failed. I’ve just found 10000 ways that won’t work.", "Thomas A. Edison"),
        arrayOf("Many of life’s failures are people who did not realize how close they were to success when they gave up.", "Thomas Edison"),
        arrayOf("Opportunity is missed by most people because it is dressed in overalls and looks like work.", "Thomas Edison"),
        arrayOf("To have a great idea, have a lot of them.", "Thomas Edison"),
        arrayOf("Never spend your money before you have it.", "Thomas Jefferson"),
        arrayOf("I’m a great believer in luck and I find the harder I work the more I have of it.", "Thomas Jefferson"),
        arrayOf("In matters of style, swim with the current. In matters of principle, stand like a rock.", "Thomas Jefferson"),
        arrayOf("Make your team feel respected, empowered and genuinely excited about the company’s mission.", "Tim Westergen"),
        arrayOf("Management is about arranging and telling. Leadership is about nurturing and enhancing.", "Tom Peters"),
        arrayOf("The art of leadership is saying no, not saying yes. It is very easy to say yes.", "Tony Blair"),
        arrayOf("Chase the vision, not the money, the money will end up following you.", "Tony Hsieh"),
        arrayOf("Don’t be cocky. Don’t be flashy. There’s always someone better than you.", "Tony Hsieh"),
        arrayOf("If you do what you’ve always done, you’ll get what you’ve always gotten.", "Tony Robbins"),
        arrayOf("My responsibility is getting all my players playing for the name on the front of the jersey, not the one on the back.", "Unknown"),
        arrayOf("A truly rich man is one whose children run into his arms when his hands are empty.", "Unknown"),
        arrayOf("You can’t fall if you don’t climb. But there’s no joy in living your whole life on the ground.", "Unknown"),
        arrayOf("If you live for having it all, what you have is never enough.", "Vicki Robin"),
        arrayOf("Even if you don’t have the perfect idea to begin with, you can likely adapt.", "Victoria Ransom"),
        arrayOf("The only place where success comes before work is in the dictionary.", "Vidal Sassoon"),
        arrayOf("Winners never quit and quitters never win.", "Vince Lombardi"),
        arrayOf("Winning isn’t everything, but wanting to win is.", "Vince Lombardi"),
        arrayOf("Leaders aren't born, they are made. And they are made just like anything else, through hard work. And that's the price we'll have to pay to achieve that goal, or any goal.", "Vince Lombardi"),
        arrayOf("It is time for us to stand and cheer for the doer, the achiever, the one who recognizes the challenge and does something about it.", "Vince Lombardi"),
        arrayOf("I would rather die of passion than of boredom.", "Vincent van Gogh"),
        arrayOf("If you hear a voice within you say you cannot paint, then by all means paint and that voice will be silenced.", "Vincent van Gogh"),
        arrayOf("Fortune sides with him who dares.", "Virgil"),
        arrayOf("Definiteness of purpose is the starting point of all achievement.", "W. Clement Stone"),
        arrayOf("The way to get started is to quit talking and start doing.", "Walt Disney"),
        arrayOf("The final test of a leader is that he leaves behind him in other men, the conviction and the will to carry on.", "Walter Lippman"),
        arrayOf("The most dangerous leadership myth is that leaders are born-that there is a genetic factor to leadership. That's nonsense. In fact, the opposite is true. Leaders are made rather than born.", "Warren Bennis"),
        arrayOf("I am reminded how hollow the label of leadership sometimes is and how heroic followership can be.", "Warren Bennis"),
        arrayOf("Leadership is the capacity to translate vision into reality.", "Warren Bennis"),
        arrayOf("Too many companies believe people are interchangeable. Truly gifted people never are. They have unique talents. Such people cannot be forced into roles they are not suited for, nor should they be. Effective leaders allow great people to do the work they were born to do.", "Warren Bennis"),
        arrayOf("I will tell you the secret to getting rich on Wall Street. You try to be greedy when others are fearful. And you try to be fearful when others are greedy.", "Warren Buffett"),
        arrayOf("I dont look to jump over 7-foot bars. I look around for 1-foot bars that I can step over.", "Warren Buffett"),
        arrayOf("I never attempt to make money on the stock market. I buy on the assumption that they could close the market the next day and not reopen it for ten years.", "Warren Buffett"),
        arrayOf("The Stock Market is designed to transfer money from the Active to the Patient.", "Warren Buffett"),
        arrayOf("I skate to where the puck is going to be, not where it has been.", "Wayne Gretzky"),
        arrayOf("You miss 100% of the shots you don’t take.", "Wayne Gretzky"),
        arrayOf("Education is the mother of leadership.", "Wendell Willkie"),
        arrayOf("Too many people spend money they earned, to buy things they don't want, to impress people that they don't like.", "Will Rogers"),
        arrayOf("Before you speak, listen. Before you write, think. Before you spend, earn. Before you invest, investigate. Before you criticize, wait. Before you pray, forgive. Before you quit, try. Before you retire, save. Before you die, give.", "William A. Ward"),
        arrayOf("Never, never, never give up.", "Winston Churchill"),
        arrayOf("We make a living by what we get, but we make a life by what we give.", "Winston Churchill"),
        arrayOf("If you’re going through hell, keep going.", "Winston Churchill"),
        arrayOf("Courage is what it takes to stand up and speak, courage is also what it takes to sit down and listen.", "Winston Churchill"),
        arrayOf("You must put your head into the lion’s mouth if the performance is to be a success.", "Winston Churchill"),
        arrayOf("A pessimist sees the difficulty in every opportunity, an optimist sees the opportunity in every difficulty.", "Winston Churchill"),
        arrayOf("Success is walking from failure to failure with no loss of enthusiasm.", "Winston Churchill"),
        arrayOf("The nation will find it very hard to look up to the leaders who are keeping their ears to the ground.", "Winston Churchill"),
        arrayOf("Leadership does not always wear the harness of compromise.", "Woodrow Wilson"),
        arrayOf("Eighty percent of success is showing up.", "Woody Allen"),
        arrayOf("People often say that motivation doesn’t last. Well, neither does bathing. That’s why we recommend it daily.", "Zig Ziglar"),
        arrayOf("You can have everything you want in life if you just help enough people get what they want in life.", "Zig Ziglar"),
        arrayOf("If people like you, they’ll listen to you, but if they trust you, they’ll do business with you.", "Zig Ziglar"),
        arrayOf("Research indicates that workers have three prime needs: interesting work, recognition for doing a good job, and being let in on things that are going on in the company.", "Zig Ziglar"),
        arrayOf("If you can dream it, you can achieve it.", "Zig Ziglar"),
        arrayOf("Rich people have small TVs and big libraries, and poor people have small libraries and big TVs.", "Zig Ziglar"),
        arrayOf("It's not the situation, but whether we react (negative) or respond (positive) to the situation that's important.", "Zig Ziglar"),
        arrayOf("One can get anything if he is willing to help enough others get what they want.", "Zig Ziglar"),
    )
}